name: Build and Deploy backend api gateway

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - "backend/api-gateway/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/api-gateway
          file: ./backend/api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop backend-api-gateway || true
            docker rm backend-api-gateway || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-gateway:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-gateway:latest
            docker run -d --name backend-api-gateway -p 3000:3000 \
            -e PRODUCT_SERVICE_URL=http://34.58.241.34:3001 \
            -e VOUCHERS_SERVICE_URL=http://34.58.241.34:3002 \
            -e ORDER_SERVICE_URL="http://34.58.241.34:3004" \
            -e USERS_SERVICE_URL=http://34.58.241.34:3005 \
            -e PAYMENT_SERVICE_URL=http://34.58.241.34:3007 \
            -e ACCOUNTS_SERVICE_URL=http://34.58.241.34:3008 \
            -e SEARCH_SERVICE_URL=http://34.58.241.34:3009 \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-api-gateway:latest
