name: Build and Deploy frontend buyer

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - 'frontend/buyer/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/buyer
          file: ./frontend/buyer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-buyer:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop frontend-buyer || true
            docker rm frontend-buyer || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/frontend-buyer:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-buyer:latest
            docker run -d --name frontend-buyer -p 8000:8000 \
            -e "VITE_API_GATEWAY_URL=http://34.58.241.34:3000" \
            -e "VITE_AUTH_SERVICE_URL=http://34.58.241.34:3003" \
            -e "VITE_SELLER_URL=http://34.58.241.34:8001" \
            -e "VITE_BUYER_URL=http://34.58.241.34:8000"  \
            -e "VITE_PRODUCT_SERVICE_URL=http://34.58.241.34:3001" \
            -e "VITE_ACCOUNT_SERVICE_URL=http://34.58.241.34:3005" \
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-buyer:latest
