name: Build and Deploy backend search service

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - "backend/search-service/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/search-service
          file: ./backend/search-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-search-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Print dockerhub username
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop backend-search-service || true
            docker rm backend-search-service || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/backend-search-service:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-search-service:latest
            docker run -d --name backend-search-service -p 3009:3009 \

            -e ELASTICSEARCH_NODE="https://34.69.91.173:9200" \
            -e ELASTICSEARCH_USERNAME="elastic" \
            -e ELASTICSEARCH_PASSWORD="123456789" \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-search-service:latest
