name: Build and Deploy backend accounts service

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - 'backend/accounts-service/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/accounts-service
          file: ./backend/accounts-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-accounts-service:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop backend-accounts-service || true
            docker rm backend-accounts-service || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/backend-accounts-service:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-accounts-service:latest
            docker run -d --name backend-accounts-service -p 3008:3008 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e KEYCLOAK_BASE_URL=${{ secrets.KEYCLOAK_BASE_URL }} \
            -e KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} \
            -e KEYCLOAK_ADMIN_USERNAME=${{ secrets.KEYCLOAK_ADMIN_USERNAME }} \
            -e KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }} \
            -e KEYCLOAK_ADMIN_CLIENT_ID=${{ secrets.KEYCLOAK_ADMIN_CLIENT_ID }} \
            -e KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} \
            -e KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }} \
            -e REDIRECT_GATEWAY="127.11.0.1" \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-accounts-service:latest
