name: Build and Deploy frontend seller

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - 'frontend/seller/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/seller
          file: ./frontend/seller/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop frontend-seller || true
            docker rm frontend-seller || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
            docker run -d --name frontend-seller -p 8001:8000 ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
