name: Build and Deploy backend voucher service

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - 'backend/voucher-service/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/voucher-service
          file: ./backend/voucher-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-voucher-service:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker stop backend-voucher-service || true
            docker rm backend-voucher-service || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/backend-voucher-service:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-voucher-service:latest
            docker run -d --name backend-voucher-service -p 3002:3002 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e PORT=3002 \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-voucher-service:latest