name: Build and Deploy frontend seller

on:
  push:
    # paths-ignore:
    #   - '.github/**'
    paths:
      - 'frontend/seller/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/seller/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
      
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
            docker stop frontend-seller || true
            docker rm frontend-seller || true
            docker run -d --name frontend-seller -p 80:8000 ${{ secrets.DOCKERHUB_USERNAME }}/frontend-seller:latest
